name: DevSecOps Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Security Analysis
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install
        cd server && npm install
    
    - name: Run npm audit (Dependency vulnerabilities)
      run: npm audit --audit-level=moderate
      continue-on-error: true
    
    - name: Check for secrets in code
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
      continue-on-error: true
    
    - name: SAST - Static Application Security Testing
      run: |
        npx eslint . --ext .js,.jsx --max-warnings 50
      continue-on-error: true
    
    - name: Check for outdated packages
      run: npm outdated
      continue-on-error: true

  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality Check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run linting
      run: npx eslint . --ext .js,.jsx
      continue-on-error: true

  build-test:
    runs-on: ubuntu-latest
    name: Build and Test
    needs: [security-scan, code-quality]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build application
      run: npm run build
      continue-on-error: true
    
    - name: Security summary
      run: |
        echo "✅ DevSecOps Pipeline Completed"
        echo "Security checks performed:"
        echo "- Dependency vulnerability scanning"
        echo "- Secret detection"
        echo "- Static code analysis"
        echo "- Code quality checks"